### ISSUE TITLE
defaultErrorText not working

### ISSUE THREAD

**Issue by soufiane0123** [Michelphoenix98/flutter_survey#4]
![image](https://user-images.githubusercontent.com/111284741/200274528-856f8247-4c33-4332-9b56-aa255ece280a.png)

**Comment by Michelphoenix98** [comment]
My apologies...I overlooked this parameter. I have however added a field to the [Question] model so that each question can have it's own message. But I suppose you would like to have control over the default message itself. I shall fix it asap! Stay tuned. Thank you so much raising this issue! I really appreciate it!

**Comment by Michelphoenix98** [comment]
I believe I've fixed the issue now. Take the latest and let me know if you run into any other issues.
